packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  tesseract.js: true
  workerd: true

minimumReleaseAgeExclude:
  - miniflare@5.20260801.0-alpha
  - wrangler@4.119.0

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - tesseract.js
  - workerd
