packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  tesseract.js: true

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - tesseract.js
